version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports: 
      - "6379:6379"
    networks:
      - test
  psql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=admin
      - POSTGRES_DB=main
      - POSTGRES_PASSWORD=123456Aa
    ports:
      - "5432:5432"
    networks:
      - test
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  # server:
  #   restart: unless-stopped
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - psql
  #   ports:
  #     - "6969:6969"
  #   networks:
  #     - test

networks:
  test:
    driver: bridge

volumes:
  postgres-data: